### PR TITLE
Upgrade html-sketchapp to v2.0.0

### PR DESCRIPTION
**Pull request by kojiwakayama**
Closes https://github.com/chrisvxd/story2sketch/issues/8 and https://github.com/chrisvxd/story2sketch/issues/14

### CODE REVIEW

**Comment by kdzwinel** [comment]
html-sketchapp is now available on [npm](https://www.npmjs.com/package/@brainly/html-sketchapp) so I suggest pulling it from there ;)

**Comment by kojiwakayama** [comment]
Thanks! @kdzwinel

**Comment by kdzwinel** [comment]
@kojiwakayama np! 2.0.0 does introduce a [breaking change though](https://github.com/brainly/html-sketchapp/releases/tag/v2.0.0) (sorry, I should have mentioned that), so updating to 2.0 may require a bit more work. Update to 1.1.1 should be painless though.

**Comment by kojiwakayama** [comment]
Oh, thanks for letting me know @kdzwinel I changed the version to 1.1.1 for now. Looking now into the upgrade to 2.0.

**Comment by kojiwakayama** [comment]
Upgraded to 2.0 @kdzwinel @chrisvxd

**Comment by chrisvxd** [comment]
Hey @kojiwakayama! Thanks for the PR! I’m on holiday at the moment but will test this out when I’m next at a computer, either later this week, or the next week at the latest.

**Comment by chrisvxd** [comment]
Excellent work, thanks @kojiwakayama!

**Pull request merged**
