### PR TITLE
add fix for pseudo elements

### PR DESCRIPTION
**Pull request by hipstersmoothie**
`html-sketchapp` doesn't support pseudo elements https://github.com/brainly/html-sketchapp/issues/20.

A fix for this is proposed by https://github.com/brainly/html-sketchapp/issues/20#issuecomment-343702277 but the maintainer doesn't want to add it due to it not covering all cases. 

I think this would be a good place for the code to live though. I have test it with the icon font that my app uses and it works pretty well. Definitely better than not rendering at all.

Currently it runs by default for every page. This behavior could be guarded by a flag though. I am willing to add this if you want @chrisvxd. Are you open to adding this?

### CODE REVIEW

**Comment by chrisvxd** [comment]
Thanks for this Andrew! I’m currently out of town but will review in the coming days.

**Comment by hipstersmoothie** [comment]
@chrisvxd any chance you  could get to this soon?

**Comment by hipstersmoothie** [comment]
@chrisvxd typo fixed!

**Comment by chrisvxd** [comment]
@hipstersmoothie 👏 thank you! Merged!

NB I squashed into conventional commit format, so you might want to reset your head to master.

**Comment by chrisvxd** [comment]
@hipstersmoothie just released `v1.4.0` with your fixes!

**Comment by hipstersmoothie** [comment]
Awesome! Thanks a lot. Sorry I didn’t notice the commit format til I was
done

**Comment by chrisvxd** [comment]
No worries about commit format! I tend to squash most PRs that come through at the moment since many people aren't familiar with conventional commits.

It's another place for me to add linting, though!

**Pull request merged**
